# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4bed855939926c45120f892f5881463bfec45480f34832465fb2582b1ec356324f95b55048c9731fcbaca886f77da9ee6c07c70f011c4be05c3c844670859133

test:
  secret_key_base: edd7b630b1ce2a90ea059503a7d5b533f51a648a9fdb4333491a17885967fa1b47d821e6de3f4b8f365a5d7e6f57dd881ef48b2ce6fb5226331c13fa9b29d0a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
